### ISSUE TITLE
Test suite failures on Debian for 0.11.10

### ISSUE THREAD

**Issue by sumnerevans** [sublime-music/sublime-music#277]
In GitLab by @baldurmen on Oct 16, 2020, 12:27

Hi!

I've worked quite a bit to get `0.11.9` uploaded in Debian and things look pretty good. I'm currently waiting for [python-typing-inspect](https://ftp-master.debian.org/new/python-typing-inspect_0.6.0-1.html), [python-marshmallow-enum](https://ftp-master.debian.org/new/python-marshmallow-enum_1.5.1-1.html) and [dataclasses-json](https://ftp-master.debian.org/new/dataclasses-json_0.5.2-1.html) to make it to the archive for me to upload the latest sublime-music version.

That said, I've hit some test suite errors and I wanted to check with you to see if you had an idea what caused those. I'm aware these might be hard for you to reproduce, since I'm using Debian packages I've built locally for python-typing-inspect, python-marshmallow-enum and dataclasses-json.

## Peewee

Using Python 3.9 (3.8 yields the same error), `peewee` seems to fail. Debian has version `3.13.1` while the latest upstream version is `3.13.3`, so I doubt the problem comes from an outdated version:

```
___________________________ test_caching_get_artist ____________________________

cache_adapter = <sublime_music.adapters.filesystem.adapter.FilesystemAdapter object at 0x7f9e8c9706d0>

    def test_caching_get_artist(cache_adapter: FilesystemAdapter):
        with pytest.raises(CacheMissError):
            cache_adapter.get_artist("1")
    
        # Simulate the artist details being retrieved from Subsonic.
        cache_adapter.ingest_new_data(
            KEYS.ARTIST,
            "1",
            SubsonicAPI.ArtistAndArtistInfo(
                id="1",
                name="Bar",
                album_count=1,
                artist_image_url="image",
                similar_artists=[
                    SubsonicAPI.ArtistAndArtistInfo(id="A", name="B"),
                    SubsonicAPI.ArtistAndArtistInfo(id="C", name="D"),
                ],
                biography="this is a bio",
                music_brainz_id="mbid",
                albums=[
                    SubsonicAPI.Album(id="1", name="Foo", _artist="Bar", artist_id="1")
                ],
            ),
        )
    
        artist = cache_adapter.get_artist("1")
        assert (
            artist.artist_image_url
            and (
                artist.id,
                artist.name,
                artist.album_count,
                artist.artist_image_url,
                artist.biography,
                artist.music_brainz_id,
            )
            == ("1", "Bar", 1, "image", "this is a bio", "mbid")
        )
>       assert artist.similar_artists == [
            SubsonicAPI.ArtistAndArtistInfo(id="A", name="B"),
            SubsonicAPI.ArtistAndArtistInfo(id="C", name="D"),
        ]

tests/adapter_tests/filesystem_adapter_tests.py:775: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <peewee.ModelSelect object at 0x7f9e8c9704c0>
other = [ArtistAndArtistInfo(name='B', id='A', albums=[], album_count=None, cover_art=None, artist_image_url=None, starred=Non...None, artist_image_url=None, starred=None, similar_artists=[], biography=None, music_brainz_id=None, last_fm_url=None)]

    def __eq__(self, other):
>       return self._hash == other._hash
E       AttributeError: 'list' object has no attribute '_hash'

/usr/lib/python3/dist-packages/peewee.py:817: AttributeError
```

## test_config_form() segfaults

This test simply segfaults, and I have not been able to get something more verbose than this :(

```
tests/adapter_tests/subsonic_adapter_tests.py::test_config_form Segmentation fault
E: pybuild pybuild:352: test: plugin distutils failed with: exit code=139: cd /<<PKGBUILDDIR>>/.pybuild/cpython3_3.9_sublime-music/build; python3.9 -m pytest --verbose
```

Happy to run pytest with different options or modify the test to get something more verbose if you want me to.

**Comment by sumnerevans** [comment]
Thanks for your work on this! I saw your issue & PR on the `dataclasses-json` repo, hopefully that gets accepted and merged. It seems like the maintainer of that project isn't very responsive/active these days, though.

For the peewee issue, can you try modifying the test to use a for loop with a zip of `artist.similar_artists` and the desired list and doing the assertion on each element individually? (If that works, could you also add an assertion for the length of the list?)

For the test_config_form issue, do the other tests run OK? Do you know which line of this test fails? My guess is that this has something to do with the `keyring` dependency, but that's really just a shot in the dark.

**Comment by sumnerevans** [comment]
In GitLab by @baldurmen on Oct 23, 2020, 21:33

Sorry, I've been busy trying to fix build failures with python3.9 in Debian. Sadly 3.9 has been breaking stuff right and left -_-,

So, the missing dependencies I referenced here _finally_ reached the Debian unstable archive. This means you could try to debug these issues yourself easily. Since you know the codebase much better than I, I feel this would be a better use of both our time :)

The build dependencies are [listed here](https://salsa.debian.org/python-team/packages/sublime-music/-/blob/debian/waiting_on_NEW/debian/control#L8).

Meanwhile, I tried running my build of `0.11.9` for the first time and lo and behold, `test_caching_get_artist` failing was not a false positive:

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sublime_music/adapters/manager.py", line 375, in future_fn
    return fn(*params, **kwargs)
  File "/usr/lib/python3/dist-packages/sublime_music/adapters/subsonic/adapter.py", line 562, in get_artists
    if artist_index := self._get_json(self._make_url("getArtists")).artists:
  File "/usr/lib/python3/dist-packages/sublime_music/adapters/subsonic/adapter.py", line 453, in _get_json
    return Response.from_dict(subsonic_response)
  File "/usr/lib/python3/dist-packages/dataclasses_json/api.py", line 82, in from_dict
    return _decode_dataclass(cls, kvs, infer_missing)
  File "/usr/lib/python3/dist-packages/dataclasses_json/core.py", line 201, in _decode_dataclass
    init_kwargs[field.name] = _decode_generic(field_type,
  File "/usr/lib/python3/dist-packages/dataclasses_json/core.py", line 273, in _decode_generic
    res = _decode_dataclass(type_arg, value, infer_missing)
  File "/usr/lib/python3/dist-packages/dataclasses_json/core.py", line 159, in _decode_dataclass
    field_value = kvs[field.name]
KeyError: 'ignored_articles'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 328, in _invoke_callbacks
    callback(self)
  File "/usr/lib/python3/dist-packages/sublime_music/adapters/manager.py", line 125, in _on_future_complete
    raise e
  File "/usr/lib/python3/dist-packages/sublime_music/adapters/manager.py", line 120, in _on_future_complete
    self._data = future.result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3/dist-packages/sublime_music/adapters/manager.py", line 1153, in do_get_artists
    AdapterManager._get_from_cache_or_ground_truth(
  File "/usr/lib/python3/dist-packages/sublime_music/adapters/manager.py", line 143, in result
    raise e
  File "/usr/lib/python3/dist-packages/sublime_music/adapters/manager.py", line 136, in result
    return self._future.result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 328, in _invoke_callbacks
    callback(self)
  File "/usr/lib/python3/dist-packages/sublime_music/adapters/manager.py", line 125, in _on_future_complete
    raise e
  File "/usr/lib/python3/dist-packages/sublime_music/adapters/manager.py", line 120, in _on_future_complete
    self._data = future.result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3/dist-packages/sublime_music/adapters/manager.py", line 377, in future_fn
    raise CacheMissError(partial_data=partial_data) from e
sublime_music.adapters.adapter_base.CacheMissError
2020-10-23 22:20:17,538:ERROR:concurrent.futures:_base:exception calling callback for <Future at 0x7f62f8063490 state=finished raised CacheMissError>
```

I don't see a mention of `peewee` though...

I'll probably upload `0.11.9-1` to unstable as-is for now, as it will help you debug it and let me make incremental changes.

**Comment by sumnerevans** [comment]
Hmm... I think that some of the `ignored_articles` errors may be fixed in 0.11.10.

A few more issues may be fixed in 6452cf1

**Comment by sumnerevans** [comment]
In GitLab by @baldurmen on Oct 23, 2020, 23:58

Good to know! I've just uploaded `0.11.9` and I'll try to upload `0.11.10` tomorrow and check if the master branch has less issues :)

**Comment by sumnerevans** [comment]
If you find that `master` works better, then let me know and I'll cut an actual release with the latest fixes.

**Comment by sumnerevans** [comment]
In GitLab by @baldurmen on Oct 24, 2020, 22:24

The `ignored_articles` bug is https://github.com/spl0k/supysonic/issues/194, sorry for wasting your time. I still have the same testsuite failures with `0.11.10` though.

**Comment by sumnerevans** [comment]
In GitLab by @baldurmen on Oct 25, 2020, 24:45

I've just uploaded `0.11.10-1` to the Debian archive, so it should be relatively easy for you to check the testsuite errors in a Debian unstable VM/docker image by running the testsuite on the installed package.

**Comment by sumnerevans** [comment]
I got a Debian VM up and running, and I cloned Sublime Music `master` and installed using

```
poetry install -E chromecast -E keyring -E server
```

and then ran `pytest` and I got no errors.

How can I reproduce this?

**Comment by sumnerevans** [comment]
In GitLab by @baldurmen on Oct 27, 2020, 13:19

I haven't used `poetry` before, but my guess is that it uses `pip` and not `apt` to install dependencies?

The simplest way you be to install the deps manually from the Debian archive (from unstable) and run the testsuite using `pytest` on the git checkout:

    $ apt install python3-setuptools python3-all python3-sphinx python3-sphinx-rtd-theme python3-pytest gir1.2-gtk-3.0 gir1.2-nm-1.0 gobject-introspection network-manager-dev python3-bottle python3-dataclasses-json python3-dateutil python3-deepdiff python3-fuzzywuzzy python3-gi python3-keyring python3-levenshtein python3-mpv python3-peewee python3-pychromecast python3-requests  python3-semver python3-bleach
    $ git clone https://gitlab.com/sublime-music/sublime-music
    $ cd sublime-music
    $ git checkout v0.11.10
    $ pytest-3 tests

**Comment by baldurmen** [comment]
This issue should be closed, it's stale and the actual problem is hard to understand :)

I'll open a new one with a more recent peewee failure under Debian...
