### ISSUE TITLE
AUR package maintenance sublime-music-git

### ISSUE THREAD

**Issue by exu-g** [sublime-music/sublime-music#365]
The package [sublime-music-git](https://aur.archlinux.org/packages/sublime-music-git) on the AUR needs some updates to build again. I've posted the diffs for an updated PKGBUILD in the comments, but haven't got a response yet.  
Based on the username, this project and the AUR package are maintained by the same person, which is why I'm asking here.

I'm open to co-maintaining the package on the AUR if that's something you'd want.

**Comment by sumnerevans** [comment]
I don't use Arch anymore, so I'm just going to disown the package and let you adopt it. Thanks!
