### ISSUE TITLE
Doesn't work with the new libplacebo on arch Linux

### ISSUE THREAD

**Issue by emanuelserpa** [sublime-music/sublime-music#372]
Says that libplacebo.so.208 is missing, but Arch provides a newer version now.

**Comment by edwargix** [comment]
Are you using either of the AUR packages, sublime-music or sublime-music-git?

https://aur.archlinux.org/packages/sublime-music
https://aur.archlinux.org/packages/sublime-music-git

**Comment by emanuelserpa** [comment]
`sublime-music`

Tried `sublime-music-git` but it gives an error in the testing.

PS: the error is from `python-thebuzz`, not `sublime-music-git` itself.

PS2: 
```
Traceback (most recent call last):
  File "/usr/bin/sublime-music", line 5, in <module>
    from sublime_music.__main__ import main
  File "/usr/lib/python3.10/site-packages/sublime_music/__main__.py", line 14, in <module>
    from .app import SublimeMusicApp
  File "/usr/lib/python3.10/site-packages/sublime_music/app.py", line 46, in <module>
    from .dbus import DBusManager, dbus_propagate
  File "/usr/lib/python3.10/site-packages/sublime_music/dbus/__init__.py", line 1, in <module>
    from .manager import DBusManager, dbus_propagate
  File "/usr/lib/python3.10/site-packages/sublime_music/dbus/manager.py", line 13, in <module>
    from ..players import PlayerManager
  File "/usr/lib/python3.10/site-packages/sublime_music/players/__init__.py", line 1, in <module>
    from .manager import PlayerDeviceEvent, PlayerEvent, PlayerManager
  File "/usr/lib/python3.10/site-packages/sublime_music/players/manager.py", line 8, in <module>
    from .mpv import MPVPlayer  # noqa: F401
  File "/usr/lib/python3.10/site-packages/sublime_music/players/mpv.py", line 5, in <module>
    import mpv
  File "/usr/lib/python3.10/site-packages/mpv.py", line 54, in <module>
    backend = CDLL(sofile)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libplacebo.so.208: não é possível abrir arquivo compartilhado: Arquivo ou diretório inexistente
```

Something with `python-mpv`?

**Comment by edwargix** [comment]
@emanuelserpa I bumped the pkgrel of the sublime-music package so that your AUR helper rebuilds sublime.  Can you see if that helps?

https://aur.archlinux.org/cgit/aur.git/commit/?h=sublime-music&id=d6edf63be4785c273d2764254e5fb4fa11f043a7

**Comment by edwargix** [comment]
everything seems to work for me on my Arch machine with an old gonic server and libplacebo 5.229.1-2

**Comment by edwargix** [comment]
> Says that libplacebo.so.208 is missing, but Arch provides a newer version now.

weird; mine is on 104:

```sh
$ yay -Fl libplacebo | grep usr/lib
libplacebo usr/lib/
libplacebo usr/lib/libplacebo.so
libplacebo usr/lib/libplacebo.so.104
libplacebo usr/lib/pkgconfig/
libplacebo usr/lib/pkgconfig/libplacebo.pc
```

**Comment by emanuelserpa** [comment]
Looks like the culprit is `python-mpv` that is not compatible with the new libplacebo.

**Comment by edwargix** [comment]
> Looks like the culprit is `python-mpv` that is not compatible with the new libplacebo.

Where do you see that?  Does the `python-mpv` need to be bumped?

Do you know why your libplacebo version is newer than mine?

**Comment by edwargix** [comment]
@emanuelserpa Do you know why your libplacebo version is newer than mine?

**Comment by emanuelserpa** [comment]
> @emanuelserpa Do you know why your libplacebo version is newer than mine?

Dunno. `5.229.1-2` is the latest in the repos. Maybe the package is on `IgnorePkg`?

![image](https://user-images.githubusercontent.com/934124/214470382-54353d5b-0ab7-41cc-b912-b65c2385074c.png)

Anyway, is there any plan to add sublime-music to Flathub?

**Comment by emanuelserpa** [comment]
Libplacebo 3.104 was a while back.

![image](https://user-images.githubusercontent.com/934124/214470884-8e516aad-a91b-46cb-98a9-73dff1c828cf.png)

**Comment by emanuelserpa** [comment]
Now, for some reason, it is working fine. With latest libplacebo.

Thanks!
