### ISSUE TITLE
Fedora (RPM) package or an App Image something that would be accepted?

### ISSUE THREAD

**Issue by FreedomBen** [sublime-music/sublime-music#400]
If someone were to package Sublime Music as an RPM, and/or an App Image, would that be wanted and/or accepted?

**Comment by sumnerevans** [comment]
If you would like to maintain these separately from the project, that's fine, but upstreaming such packages would not be accepted. See the following issues which have discussion of why: https://github.com/sublime-music/sublime-music/issues/348, https://github.com/sublime-music/sublime-music/issues/309

**Comment by FreedomBen** [comment]
Thanks, those links are helpful.  If they were maintained separately, could we put a link/instructions in the main project readme so that people can find it and avoid people routinely reinventing the wheel?

**Comment by sumnerevans** [comment]
Yes. We can definitely add a link.
