### ISSUE TITLE
Package as AppImage

### ISSUE THREAD

**Issue by sumnerevans** [sublime-music/sublime-music#49]
It would be nice for people to be able to try out libremsonic using an AppImage.

**Requirements:**

- [ ] Ability to build appimage locally for testing
- [ ] Automate the creation of the appimage in the CI/CD process, and add it to the release so that you can easily download it.

**Resources:**
* https://github.com/AppImage/AppImageKit/wiki/Bundling-Python-apps
* https://notabug.org/themightyglider/Python_and_pygame_AppImage_tutorial/src/master/howto_py_appimage.sh

**Comment by sumnerevans** [comment]
In GitLab by @r0bbie on May 23, 2020, 13:45

Would love to see an AppImage release. Just about managed to get Sublime running after installing via pip but this would be much better.

Thanks for building this app btw, seems to be progressing into something a lot more polished than any of the other Subsonic API-compatible desktop apps out there!

**Comment by sumnerevans** [comment]
@r0bbie thanks! My plan is to probably do this after the 1.0 release (as I expect things to be much more stable by then).

If you don't mind me asking, how did you hear about the project?

**Comment by sumnerevans** [comment]
In GitLab by @r0bbie on May 23, 2020, 14:31

I've been researching music server and client options over the last few days, and found Sublime Music via the Gonic Subsonic API implementation, they have a link on [their readme on GitHub](https://github.com/sentriz/gonic).

Was looking for a good desktop Subsonic client, and the fact Sublime is cross-platform (seen a macOS release is upcoming too!) and had a modern, clean interface appealed. Ability to cast to other devices is a big bonus too (fingers crossed for UPnP at some point as well Chromecast!)

**Comment by sumnerevans** [comment]
https://www.reddit.com/r/linux/comments/inq86r/nixbundle_builds_portable_binaries_something_like/

https://github.com/matthewbauer/nix-bundle

**Comment by nelsongraca** [comment]
is there any hope this will be implemented any time soon?

**Comment by sumnerevans** [comment]
No, however the community is welcome to do this and I'll link it from the readme and website.
